"""final_sync

Revision ID: 3110591a5be2
Revises: 
Create Date: 2026-03-21 01:13:36.136077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3110591a5be2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('user_name', sa.String(length=150), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastro_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('current_attendees', sa.Integer(), nullable=True),
    sa.Column('dishes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=180), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=150), nullable=True),
    sa.Column('reserved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['gastro_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_type'))

    op.drop_table('ai_suggestions')
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_date'))
        batch_op.drop_index(batch_op.f('idx_inventory'))

    op.drop_table('inventory_movements')
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='Opcional: solo informativo (starter, main, dessert)',
               existing_nullable=True)
        batch_op.alter_column('available_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Fecha espec??fica de disponibilidad del plato',
               existing_nullable=False)
        batch_op.alter_column('stock_total',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='Stock total disponible para esa fecha',
               existing_nullable=False,
               existing_server_default=sa.text('10'))
        batch_op.alter_column('stock_reserved',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='Unidades ya reservadas',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_active'))
        batch_op.drop_index(batch_op.f('idx_available_date'))
        batch_op.drop_index(batch_op.f('idx_stock'))

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_stock'))

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.SmallInteger(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_dish'))
        batch_op.drop_index(batch_op.f('idx_rating'))
        batch_op.drop_index(batch_op.f('unique_rating'))

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='Cantidad de unidades reservadas',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_date'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_user'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_date'), ['reservation_date'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Cantidad de unidades reservadas',
               existing_nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_rating'), ['user_id', 'dish_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('idx_dish'), ['dish_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('rating',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=False)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_stock'), ['quantity', 'minimum_stock'], unique=False)
        batch_op.alter_column('last_updated',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))

    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_stock'), ['stock_total', 'stock_reserved'], unique=False)
        batch_op.create_index(batch_op.f('idx_available_date'), ['available_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_active'), ['is_active'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('stock_reserved',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Unidades ya reservadas',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('stock_total',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Stock total disponible para esa fecha',
               existing_nullable=False,
               existing_server_default=sa.text('10'))
        batch_op.alter_column('available_date',
               existing_type=sa.DATE(),
               comment='Fecha espec??fica de disponibilidad del plato',
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=20),
               comment='Opcional: solo informativo (starter, main, dessert)',
               existing_nullable=True)

    op.create_table('inventory_movements',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('inventory_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('movement_type', mysql.ENUM('in', 'out'), nullable=False),
    sa.Column('quantity', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('reason', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('inventory_movements_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name=op.f('inventory_movements_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_inventory'), ['inventory_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_date'), ['created_at'], unique=False)

    op.create_table('ai_suggestions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('suggestion_type', mysql.ENUM('menu', 'inventory', 'optimization'), nullable=False),
    sa.Column('content', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'accepted', 'rejected'), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('reviewed_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('ai_suggestions_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ai_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_type'), ['suggestion_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)

    op.drop_table('event_reservations')
    op.drop_table('gastro_events')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
