import type { MenuItem, Rating, InventoryItem } from "./types"

export const mockMenuItems: MenuItem[] = [
  {
    id: "1",
    name: "Ensalada Mediterránea",
    description: "Ensalada fresca con tomate, pepino, aceitunas y queso feta",
    category: "entrante",
    allergens: ["lácteos"],
    imageUrl: "/placeholder.svg?height=200&width=300",
    available: true,
  },
  {
    id: "2",
    name: "Gazpacho Andaluz",
    description: "Sopa fría de tomate con verduras frescas",
    category: "entrante",
    allergens: ["gluten"],
    imageUrl: "/placeholder.svg?height=200&width=300",
    available: true,
  },
  {
    id: "3",
    name: "Pollo al Horno con Patatas",
    description: "Pollo asado con patatas y hierbas aromáticas",
    category: "principal",
    allergens: [],
    imageUrl: "/placeholder.svg?height=200&width=300",
    available: true,
  },
  {
    id: "4",
    name: "Paella de Verduras",
    description: "Arroz con verduras frescas de temporada",
    category: "principal",
    allergens: ["gluten"],
    imageUrl: "/placeholder.svg?height=200&width=300",
    available: true,
  },
  {
    id: "5",
    name: "Flan Casero",
    description: "Flan tradicional con caramelo",
    category: "postre",
    allergens: ["lácteos", "huevo"],
    imageUrl: "/placeholder.svg?height=200&width=300",
    available: true,
  },
  {
    id: "6",
    name: "Fruta de Temporada",
    description: "Selección de frutas frescas",
    category: "postre",
    allergens: [],
    imageUrl: "/placeholder.svg?height=200&width=300",
    available: true,
  },
]

export const mockInventory: InventoryItem[] = [
  {
    id: "1",
    name: "Tomates",
    quantity: 25,
    unit: "kg",
    minStock: 10,
    category: "Verduras",
    lastUpdated: new Date(),
  },
  {
    id: "2",
    name: "Pollo",
    quantity: 15,
    unit: "kg",
    minStock: 8,
    category: "Carnes",
    lastUpdated: new Date(),
  },
  {
    id: "3",
    name: "Arroz",
    quantity: 5,
    unit: "kg",
    minStock: 15,
    category: "Cereales",
    lastUpdated: new Date(),
  },
  {
    id: "4",
    name: "Huevos",
    quantity: 48,
    unit: "unidades",
    minStock: 24,
    category: "Lácteos",
    lastUpdated: new Date(),
  },
  {
    id: "5",
    name: "Aceite de Oliva",
    quantity: 8,
    unit: "litros",
    minStock: 5,
    category: "Aceites",
    lastUpdated: new Date(),
  },
]

export const mockRatings: Rating[] = [
  {
    id: "1",
    userId: "3",
    userName: "Profesor García",
    menuItemId: "3",
    rating: 5,
    comment: "Excelente pollo, muy bien preparado",
    date: new Date("2026-01-10"),
  },
  {
    id: "2",
    userId: "3",
    userName: "Profesor García",
    menuItemId: "1",
    rating: 4,
    comment: "Ensalada fresca y sabrosa",
    date: new Date("2026-01-09"),
  },
]
